# 4. Data Understanding


> **Dataset note:** This project uses a synthetic OTT viewer-behaviour dataset for educational analysis.  
> **Hotstar is used only as the business case/scenario; the data is not claimed to be proprietary Hotstar data.**

**Allowed tools:** Python, NumPy, Pandas, Matplotlib, Seaborn.  
**Not used:** Scikit-learn, Plotly, Power BI, Tableau, machine learning, or statistical libraries beyond NumPy/Pandas.

## Process Performed
I inspected numerical/categorical columns, missing values, duplicates, descriptive statistics, category cardinality, average watch percentage, and average episode duration.

In [1]:
# PROCESS: Load the CSV into a Pandas DataFrame and verify that the file loaded correctly.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

DATA_PATH = "ott_viewer_dropoff_retention_us_v1.0.csv"
df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (33171, 23)

,show_id,title,platform,genre,release_year,season_number,episode_number,episode_duration_min,pacing_score,hook_strength,dialogue_density,visual_intensity,avg_watch_percentage,pause_count,rewind_count,skip_intro,cognitive_load,attention_required,night_watch_safe,drop_off,drop_off_probability,retention_risk,dataset_version
0,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,1,48,4,5,high,5,39,3,0,0,9,high,0,1,0.649,high,v1.0
1,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,2,55,5,4,low,8,55,3,3,1,5,medium,0,0,0.473,medium,v1.0
2,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,3,51,4,8,high,7,46,4,2,0,9,high,0,0,0.583,medium,v1.0
3,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,4,50,4,7,medium,3,50,4,1,0,7,high,0,0,0.520,medium,v1.0
4,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,5,52,4,3,low,4,35,3,0,1,7,high,0,1,0.638,high,v1.0

## Dataset Structure

In [2]:
# KERNEL-SAFE SETUP
# Keep plotting memory controlled while preserving the analysis.
import gc

MAX_PLOT_ROWS = 5000

def safe_sample(data, n=MAX_PLOT_ROWS, random_state=42):
    """Use the full data when small; otherwise use a reproducible sample for plotting."""
    return data if len(data) <= n else data.sample(n=n, random_state=random_state)

def finish_plot():
    """Render and release the current Matplotlib figure."""
    plt.tight_layout()
    plt.show()
    plt.close()
    gc.collect()

In [3]:
# PROCESS: Separate numerical and categorical columns to understand the dataset structure.
print("Number of rows:", len(df))
print("Number of columns:", df.shape[1])

numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()

print("\nNumerical columns:")
print(numeric_cols)

print("\nCategorical columns:")
print(categorical_cols)

Number of rows: 33171
Number of columns: 23

Numerical columns:
['show_id', 'release_year', 'season_number', 'episode_number', 'episode_duration_min', 'pacing_score', 'hook_strength', 'visual_intensity', 'avg_watch_percentage', 'pause_count', 'rewind_count', 'skip_intro', 'cognitive_load', 'night_watch_safe', 'drop_off', 'drop_off_probability']

Categorical columns:
['title', 'platform', 'genre', 'dialogue_density', 'attention_required', 'retention_risk', 'dataset_version']

## Missing Values and Duplicates

In [4]:
# PROCESS: Audit missing values before deciding whether any treatment is required.
missing = df.isna().sum().sort_values(ascending=False)
print("Missing values by column:")
display(missing[missing > 0])

duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Missing values by column:

Series([], dtype: int64)

Duplicate rows: 0

## Descriptive Statistics

In [5]:
# PROCESS: Perform this analysis step and inspect the resulting table/output before drawing conclusions.
display(df.describe(include="all").T)

print("Average watch percentage:", round(df["avg_watch_percentage"].mean(), 2))
print("Average episode duration:", round(df["episode_duration_min"].mean(), 2), "minutes")

                        count unique        top   freq          mean           std     min      25%      50%      75%       max
show_id               33171.0    NaN        NaN    NaN  63698.539688  65206.256887    36.0  15226.0  35024.0  80885.0  305062.0
title                   33171    487  Sazae-san   2650           NaN           NaN     NaN      NaN      NaN      NaN       NaN
platform                33171     28    Netflix  12270           NaN           NaN     NaN      NaN      NaN      NaN       NaN
genre                   33171     16  Animation  10028           NaN           NaN     NaN      NaN      NaN      NaN       NaN
release_year          33171.0    NaN        NaN    NaN   2000.739743      15.75047  1952.0   1992.0   2004.0   2012.0    2025.0
season_number         33171.0    NaN        NaN    NaN           1.0           0.0     1.0      1.0      1.0      1.0       1.0
episode_number        33171.0    NaN        NaN    NaN    423.718881     557.68846     1.0     27.0    178.0    611.0    2650.0
episode_duration_min  33171.0    NaN        NaN    NaN     37.660667     22.899741     1.0     24.0     33.0     49.0    1225.0
pacing_score          33171.0    NaN        NaN    NaN      5.397908      1.230418     3.0      4.0      5.0      6.0       8.0
hook_strength         33171.0    NaN        NaN    NaN      5.525158      1.730098     3.0      4.0      6.0      7.0      10.0
dialogue_density        33171      3       high  11115           NaN           NaN     NaN      NaN      NaN      NaN       NaN
visual_intensity      33171.0    NaN        NaN    NaN      6.009436       1.99437     3.0      4.0      6.0      8.0       9.0
avg_watch_percentage  33171.0    NaN        NaN    NaN     56.805764        12.577    13.0     48.0     57.0     66.0     100.0
pause_count           33171.0    NaN        NaN    NaN      3.102921      1.866938     0.0      2.0      3.0      4.0      10.0
rewind_count          33171.0    NaN        NaN    NaN      2.003497      1.548391     0.0      1.0      2.0      3.0       8.0
skip_intro            33171.0    NaN        NaN    NaN      0.493262      0.499962     0.0      0.0      0.0      1.0       1.0
cognitive_load        33171.0    NaN        NaN    NaN      6.196015      1.322146     4.0      5.0      7.0      7.0       9.0
attention_required      33171      2       high  16878           NaN           NaN     NaN      NaN      NaN      NaN       NaN
night_watch_safe      33171.0    NaN        NaN    NaN      0.015887      0.125042     0.0      0.0      0.0      0.0       1.0
drop_off              33171.0    NaN        NaN    NaN      0.144825       0.35193     0.0      0.0      0.0      0.0       1.0
drop_off_probability  33171.0    NaN        NaN    NaN      0.478433      0.107382    0.12      0.4    0.471    0.553     0.831
retention_risk          33171      3     medium  27402           NaN           NaN     NaN      NaN      NaN      NaN       NaN
dataset_version         33171      1       v1.0  33171           NaN           NaN     NaN      NaN      NaN      NaN       NaN

Average watch percentage: 56.81
Average episode duration: 37.66 minutes

## Cardinality Check

In [6]:
# PROCESS: Perform this analysis step and inspect the resulting table/output before drawing conclusions.
for col in ["title", "platform", "genre", "attention_required", "retention_risk"]:
    print(f"{col}: {df[col].nunique(dropna=False)} unique values")

title: 487 unique values
platform: 28 unique values
genre: 16 unique values
attention_required: 2 unique values
retention_risk: 3 unique values

### Interpretation Note
The outputs above describe patterns in the supplied **synthetic episode-level dataset**. They should support business hypotheses and content investigation, not be presented as causal proof or proprietary Hotstar findings.

## Data Dictionary

The table below documents the analytical meaning of the supplied columns so another analyst or recruiter can understand the dataset without referring back to the project brief.

In [7]:
# PROCESS: Build a compact data dictionary from the project specification.
data_dictionary = pd.DataFrame({
    "Column": [
        "show_id", "title", "platform", "genre", "release_year",
        "season_number", "episode_number", "episode_duration_min",
        "pacing_score", "hook_strength", "dialogue_density",
        "visual_intensity", "avg_watch_percentage", "pause_count",
        "rewind_count", "skip_intro", "cognitive_load",
        "attention_required", "night_watch_safe", "drop_off",
        "drop_off_probability", "retention_risk"
    ],
    "Meaning": [
        "Unique show identifier", "Show title", "Streaming platform",
        "Content genre", "Release year", "Season number", "Episode number",
        "Episode duration in minutes", "Pacing score", "Opening hook strength",
        "Dialogue density", "Visual intensity", "Average percentage watched",
        "Number of pauses", "Number of rewinds", "Whether the intro was skipped",
        "Cognitive load", "Attention requirement", "Suitable for late-night watching",
        "Drop-off indicator", "Probability of viewer drop-off", "Retention-risk category"
    ]
})

display(data_dictionary)

                  Column                           Meaning
0                show_id            Unique show identifier
1                  title                        Show title
2               platform                Streaming platform
3                  genre                     Content genre
4           release_year                      Release year
5          season_number                     Season number
6         episode_number                    Episode number
7   episode_duration_min       Episode duration in minutes
8           pacing_score                      Pacing score
9          hook_strength             Opening hook strength
10      dialogue_density                  Dialogue density
11      visual_intensity                  Visual intensity
12  avg_watch_percentage        Average percentage watched
13           pause_count                  Number of pauses
14          rewind_count                 Number of rewinds
15            skip_intro     Whether the intro was skipped
16        cognitive_load                    Cognitive load
17    attention_required             Attention requirement
18      night_watch_safe  Suitable for late-night watching
19              drop_off                Drop-off indicator
20  drop_off_probability    Probability of viewer drop-off
21        retention_risk           Retention-risk category

## Professional Data-Quality Summary

This compact table brings together data type, missingness, and cardinality checks. It makes the dataset audit easier to review and avoids treating missing-value checks as an isolated step.

In [8]:
# Create one reusable data-quality summary table.
data_quality = pd.DataFrame({
    "data_type": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique(dropna=False)
})

display(data_quality)

print("Exact duplicate rows:", df.duplicated().sum())

                     data_type  missing_count  missing_pct  unique_values
show_id                  int64              0          0.0            489
title                      str              0          0.0            487
platform                   str              0          0.0             28
genre                      str              0          0.0             16
release_year           float64              0          0.0             65
season_number            int64              0          0.0              1
episode_number           int64              0          0.0           2650
episode_duration_min     int64              0          0.0            154
pacing_score             int64              0          0.0              6
hook_strength            int64              0          0.0              8
dialogue_density           str              0          0.0              3
visual_intensity         int64              0          0.0              7
avg_watch_percentage     int64              0          0.0             84
pause_count              int64              0          0.0             11
rewind_count             int64              0          0.0              9
skip_intro               int64              0          0.0              2
cognitive_load           int64              0          0.0              5
attention_required         str              0          0.0              2
night_watch_safe         int64              0          0.0              2
drop_off                 int64              0          0.0              2
drop_off_probability   float64              0          0.0            610
retention_risk             str              0          0.0              3
dataset_version            str              0          0.0              1

Exact duplicate rows: 0

## Memory Usage

Memory inspection is a useful Python practice because it shows how much RAM the DataFrame consumes and helps identify whether data types should be optimized in larger real-world projects.

In [9]:
# Deep memory usage includes Python object/string storage.
df.info(memory_usage="deep")

memory_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nTotal DataFrame memory usage: {memory_mb:.2f} MB")

<class 'pandas.DataFrame'>
RangeIndex: 33171 entries, 0 to 33170
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   show_id               33171 non-null  int64
 1   title                 33171 non-null  str
 2   platform              33171 non-null  str
 3   genre                 33171 non-null  str
 4   release_year          33171 non-null  float64
 5   season_number         33171 non-null  int64
 6   episode_number        33171 non-null  int64
 7   episode_duration_min  33171 non-null  int64
 8   pacing_score          33171 non-null  int64
 9   hook_strength         33171 non-null  int64
 10  dialogue_density      33171 non-null  str
 11  visual_intensity      33171 non-null  int64
 12  avg_watch_percentage  33171 non-null  int64
 13  pause_count           33171 non-null  int64
 14  rewind_count          33171 non-null  int64
 15  skip_intro            33171 non-null  int64
 16  cognitive_load        33171 non-null  int64
 17  attention_required    33171 non-null  str
 18  night_watch_safe      33171 non-null  int64
 19  drop_off              33171 non-null  int64
 20  drop_off_probability  33171 non-null  float64
 21  retention_risk        33171 non-null  str
 22  dataset_version       33171 non-null  str
dtypes: float64(2), int64(14), str(7)
memory usage: 7.4 MB

Total DataFrame memory usage: 7.41 MB

## Identifier Validation

`show_id` identifies a show, so it should not be assumed to uniquely identify an episode.  
For episode-level integrity, the combination of show, season, and episode number is more meaningful.

In [10]:
print("Unique show IDs:", df["show_id"].nunique())
print("Unique titles:", df["title"].nunique())

show_title_check = (
    df.groupby("show_id")["title"]
    .nunique()
    .sort_values(ascending=False)
)

print("\nMaximum number of titles attached to one show_id:",
      show_title_check.max())

episode_key_cols = ["show_id", "season_number", "episode_number"]

duplicate_episode_keys = df.duplicated(
    subset=episode_key_cols,
    keep=False
).sum()

print("Rows involved in duplicate episode keys:", duplicate_episode_keys)

Unique show IDs: 489
Unique titles: 487

Maximum number of titles attached to one show_id: 1
Rows involved in duplicate episode keys: 2568

## Column and Row Naming Convention

To keep the notebook professional and readable, column names should follow a consistent **snake_case** convention:

- lowercase letters
- spaces replaced with underscores
- special characters removed
- repeated underscores collapsed
- leading/trailing underscores removed

Row labels should also be explicit. For this project, the DataFrame index is named `row_id` so printed tables clearly distinguish the row label from actual dataset columns.

In [11]:
import re

def clean_column_name(column_name):
    """
    Convert a raw column label to a consistent snake_case name.

    Example:
        "Average Watch Percentage" -> "average_watch_percentage"
    """
    name = str(column_name).strip().lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    name = re.sub(r"_+", "_", name)
    return name.strip("_")


def standardize_column_names(data):
    """
    Return a copy of the DataFrame with standardized column names.
    The original DataFrame is not modified.
    """
    result = data.copy()
    result.columns = [clean_column_name(col) for col in result.columns]
    return result


def set_row_index_name(data, index_name="row_id"):
    """
    Return a copy of the DataFrame with a descriptive index name.
    This does not alter the number or order of rows.
    """
    result = data.copy()
    result.index.name = index_name
    return result


# Apply naming standards.
df = standardize_column_names(df)
df = set_row_index_name(df, "row_id")

print("Standardized column names:")
print(df.columns.tolist())

print("\nIndex name:", df.index.name)
display(df.head())

Standardized column names:
['show_id', 'title', 'platform', 'genre', 'release_year', 'season_number', 'episode_number', 'episode_duration_min', 'pacing_score', 'hook_strength', 'dialogue_density', 'visual_intensity', 'avg_watch_percentage', 'pause_count', 'rewind_count', 'skip_intro', 'cognitive_load', 'attention_required', 'night_watch_safe', 'drop_off', 'drop_off_probability', 'retention_risk', 'dataset_version']

Index name: row_id

,show_id,title,platform,genre,release_year,season_number,episode_number,episode_duration_min,pacing_score,hook_strength,dialogue_density,visual_intensity,avg_watch_percentage,pause_count,rewind_count,skip_intro,cognitive_load,attention_required,night_watch_safe,drop_off,drop_off_probability,retention_risk,dataset_version
row_id,,,,,,,,,,,,,,,,,,,,,,,
0,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,1,48,4,5,high,5,39,3,0,0,9,high,0,1,0.649,high,v1.0
1,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,2,55,5,4,low,8,55,3,3,1,5,medium,0,0,0.473,medium,v1.0
2,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,3,51,4,8,high,7,46,4,2,0,9,high,0,0,0.583,medium,v1.0
3,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,4,50,4,7,medium,3,50,4,1,0,7,high,0,0,0.520,medium,v1.0
4,66732,Stranger Things,Netflix,Sci-Fi & Fantasy,2016.0,1,5,52,4,3,low,4,35,3,0,1,7,high,0,1,0.638,high,v1.0

## Analytical Column Roles

Pandas data types alone do not tell us how a variable should be analyzed.  
For example, `show_id` is stored as an integer but is an **identifier**, while `drop_off` is numeric but is a **binary indicator**.

Separating variables by analytical role prevents IDs and flags from being treated as continuous measurements.

In [12]:
identifier_columns = [
    "show_id"
]

binary_columns = [
    "skip_intro",
    "night_watch_safe",
    "drop_off"
]

categorical_columns = [
    "title",
    "platform",
    "genre",
    "dialogue_density",
    "attention_required",
    "retention_risk",
    "dataset_version"
]

ordinal_or_discrete_columns = [
    "release_year",
    "season_number",
    "episode_number",
    "pacing_score",
    "hook_strength",
    "visual_intensity",
    "pause_count",
    "rewind_count",
    "cognitive_load"
]

continuous_columns = [
    "episode_duration_min",
    "avg_watch_percentage",
    "drop_off_probability"
]

print("Identifiers:", identifier_columns)
print("Binary indicators:", binary_columns)
print("Categorical:", categorical_columns)
print("Ordinal/discrete numeric:", ordinal_or_discrete_columns)
print("Continuous numeric:", continuous_columns)

Identifiers: ['show_id']
Binary indicators: ['skip_intro', 'night_watch_safe', 'drop_off']
Categorical: ['title', 'platform', 'genre', 'dialogue_density', 'attention_required', 'retention_risk', 'dataset_version']
Ordinal/discrete numeric: ['release_year', 'season_number', 'episode_number', 'pacing_score', 'hook_strength', 'visual_intensity', 'pause_count', 'rewind_count', 'cognitive_load']
Continuous numeric: ['episode_duration_min', 'avg_watch_percentage', 'drop_off_probability']

## Title-to-Show-ID Validation

A title is not always a unique show identifier.  
The dataset contains titles that correspond to more than one `show_id`, so show-level analysis should group by **both `show_id` and `title`** rather than title alone.

In [13]:
title_show_counts = (
    df.groupby("title")["show_id"]
    .nunique()
    .sort_values(ascending=False)
)

multi_id_titles = title_show_counts[title_show_counts > 1]

print("Titles linked to more than one show_id:", len(multi_id_titles))
display(multi_id_titles)

if len(multi_id_titles) > 0:
    display(
        df[df["title"].isin(multi_id_titles.index)]
        [["show_id", "title", "platform", "release_year"]]
        .drop_duplicates()
        .sort_values(["title", "show_id"])
    )

Titles linked to more than one show_id: 2

title
Doctor Who    2
Doraemon      2
Name: show_id, dtype: int64

        show_id       title                   platform  release_year
row_id
31505       121  Doctor Who  Britbox Apple TV Channel         1963.0
1276      57243  Doctor Who                       Hulu        2005.0
3903      57911    Doraemon                    Netflix        1979.0
5023      65733    Doraemon                       Hulu        2005.0